"""removed unique address_id on table lawyers

Revision ID: 327d9f9c360b
Revises: 45cddfec18ad
Create Date: 2022-03-08 13:45:03.687895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327d9f9c360b'
down_revision = '45cddfec18ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lawyers_address_id_key', 'lawyers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('lawyers_address_id_key', 'lawyers', ['address_id'])
    # ### end Alembic commands ###
