"""added nullable=False in address_id

Revision ID: 45cddfec18ad
Revises: 65099920de90
Create Date: 2022-03-08 09:19:49.842823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cddfec18ad'
down_revision = '65099920de90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lawyers', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lawyers', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
