"""test

Revision ID: 65099920de90
Revises: 9ac5e09d2e70
Create Date: 2022-03-07 21:16:39.791599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65099920de90'
down_revision = '9ac5e09d2e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lawyers', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lawyers', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
