"""test

Revision ID: 9ac5e09d2e70
Revises: 
Create Date: 2022-03-07 14:42:09.396803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac5e09d2e70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cep')
    )
    op.create_table('lawyers_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('cep', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['client_address.id'], ),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('address_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lawyers',
    sa.Column('oab', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['lawyers_address.id'], ),
    sa.PrimaryKeyConstraint('oab'),
    sa.UniqueConstraint('address_id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients_phone_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('client_cpf', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_cpf'], ['clients.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('lawyers_clients_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawyer_oab', sa.String(), nullable=False),
    sa.Column('client_cpf', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_cpf'], ['clients.cpf'], ),
    sa.ForeignKeyConstraint(['lawyer_oab'], ['lawyers.oab'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawyers_phone_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('lawyer_oab', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_oab'], ['lawyers.oab'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lawyers_phone_number')
    op.drop_table('lawyers_clients_table')
    op.drop_table('clients_phone_number')
    op.drop_table('lawyers')
    op.drop_table('clients')
    op.drop_table('lawyers_address')
    op.drop_table('client_address')
    # ### end Alembic commands ###
